package pl.zagranietyper;
import pl.zagranietyper.model.SettlementDecision;import java.util.*;
/** Immutable reviewed boundary for the approved TEAM_TO_SCORE wording variants. */
public final class FootballTeamToScoreVariantsReviewedSnapshot {
 public static final int EXPECTED_COUNT=4,EXPECTED_W=1,EXPECTED_L=3,EXPECTED_V=0;public static final String EXPECTED_SHA256="1c744b13dc6edb541f9442e38f500c3247142b4f67157ca5c68010abe91c2ddb";public static final Set<Long>APPROVED_IDS=Set.of(3242L,7640L,9342L,17160L);private FootballTeamToScoreVariantsReviewedSnapshot(){}
 public static Gate verify(List<FootballTeamToScoreVariantsCoverageDryRunMain.Row>rows,boolean noFalsePositives)throws Exception{Set<Long>ids=new HashSet<>();boolean unique=rows.stream().allMatch(r->ids.add(r.legId()));Set<Long>missing=new TreeSet<>(APPROVED_IDS);missing.removeAll(ids);Set<Long>unexpected=new TreeSet<>(ids);unexpected.removeAll(APPROVED_IDS);int w=count(rows,SettlementDecision.W),l=count(rows,SettlementDecision.L),v=count(rows,SettlementDecision.V);String hash=FootballTeamToScoreVariantsCoverageDryRunMain.sha(rows.stream().sorted(Comparator.comparingLong(FootballTeamToScoreVariantsCoverageDryRunMain.Row::legId)).toList());return new Gate(rows.size(),w,l,v,hash,Set.copyOf(missing),Set.copyOf(unexpected),rows.size()==EXPECTED_COUNT,EXPECTED_SHA256.equals(hash),unique&&ids.equals(APPROVED_IDS),noFalsePositives&&unique&&w==EXPECTED_W&&l==EXPECTED_L&&v==EXPECTED_V);}
 private static int count(List<FootballTeamToScoreVariantsCoverageDryRunMain.Row>rows,SettlementDecision d){return(int)rows.stream().filter(r->r.decision()==d).count();}
 public record Gate(int count,int w,int l,int v,String sha256,Set<Long>missing,Set<Long>unexpected,boolean countGate,boolean hashGate,boolean legSetGate,boolean safetyGate){public boolean ready(){return countGate&&hashGate&&legSetGate&&safetyGate;}}
}
