package pl.zagranietyper;
import com.fasterxml.jackson.databind.ObjectMapper;import pl.zagranietyper.config.*;import pl.zagranietyper.fixture.ApiFootballClient;import pl.zagranietyper.model.FootballFixtureEventsSnapshot;import pl.zagranietyper.repository.*;import pl.zagranietyper.service.*;import java.util.*;

/** Resumable fixture-events validation/backfill. This never reads or writes settlement state. */
public final class FootballFixtureEventsBackfillMain {
 private FootballFixtureEventsBackfillMain(){}
 public static void main(String[]args){Options o=parse(args);var mapper=new ObjectMapper();var db=new Database(AppConfig.fromEnvironment());var repo=new FootballFixtureEventsRepository(db,mapper);var selector=new FootballFixtureEventsTargetSelector(db);var service=new FootballFixtureEventsIngestionService(new ApiFootballClient(ApiFootballConfig.fromEnvironment(),mapper),repo,new FootballFixtureEventsNormalizer());List<Long>targets=selector.findTargets();System.out.println("targetFixtures="+targets.size());if(o.validate()>0){for(long id:targets.stream().limit(o.validate()).toList()){var s=service.inspect(id);System.out.println("VALIDATE fixture="+id+" status="+s.status()+" events="+s.events().size());s.events().stream().limit(12).forEach(e->System.out.println("  index="+e.sourceIndex()+" time="+e.minute()+"+"+e.extraMinute()+" team="+e.teamId()+" player="+e.playerId()+"/"+e.playerName()+" assist="+e.assistPlayerId()+"/"+e.assistName()+" type="+e.type()+" detail="+e.detail()));}return;}if(!o.run()){audit(targets,repo);return;}int attempted=0;for(long id:targets){if(repo.loadStatus(id).orElse(null)==FootballFixtureEventsSnapshot.FetchStatus.COMPLETE)continue;var s=service.ingest(id);attempted++;System.out.println("["+attempted+"] fixture="+id+" status="+s.status()+" events="+s.events().size());}audit(targets,repo);}
 private static void audit(List<Long>ids,FootballFixtureEventsRepository repo){EnumMap<FootballFixtureEventsSnapshot.FetchStatus,Integer>counts=new EnumMap<>(FootballFixtureEventsSnapshot.FetchStatus.class);for(var s:FootballFixtureEventsSnapshot.FetchStatus.values())counts.put(s,0);int missing=0,events=0,goals=0,cards=0,subs=0,vars=0,other=0;for(long id:ids){var st=repo.loadStatus(id);if(st.isEmpty()){missing++;continue;}counts.merge(st.get(),1,Integer::sum);for(var e:repo.loadEvents(id)){events++;String t=e.type()==null?"":e.type().toLowerCase(Locale.ROOT);if(t.equals("goal"))goals++;else if(t.equals("card"))cards++;else if(t.equals("subst"))subs++;else if(t.equals("var"))vars++;else other++;}}System.out.println("AUDIT targetFixtures="+ids.size()+" missing="+missing+" statuses="+counts);System.out.println("eventsStored="+events+" goalEvents="+goals+" cardEvents="+cards+" substitutionEvents="+subs+" varEvents="+vars+" otherEvents="+other);}
 static Options parse(String[]args){boolean run=false;int validate=0;for(String a:args==null?new String[0]:args){if("--run-all".equals(a))run=true;else if(a.startsWith("--validate="))validate=Integer.parseInt(a.substring(11));else throw new IllegalArgumentException("Usage: [--validate=N | --run-all]");}if(run&&validate>0)throw new IllegalArgumentException("choose validation or run");return new Options(run,validate);}record Options(boolean run,int validate){}
}
