package pl.zagranietyper;

import pl.zagranietyper.config.AppConfig;
import pl.zagranietyper.model.SettlementDecision;
import pl.zagranietyper.repository.*;
import pl.zagranietyper.service.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.stream.Collectors;

public final class FootballManualSettlementImportMain {
    private FootballManualSettlementImportMain() {}
    public static boolean fixtureStatusAllowed(String status,boolean override){return status == null || Set.of("FT","AET","PEN").contains(status)||override;}
    private static boolean isFinalFixtureStatus(String status){return status != null && Set.of("FT","AET","PEN").contains(status);}
    public static void main(String[] args) throws Exception {
        boolean apply=false,override=false;Long postAuthor=null;for(String arg:args){if(arg.equals("--apply"))apply=true;else if(arg.equals("--allow-nonfinal-fixture-status"))override=true;else if(arg.startsWith("--post-author="))postAuthor=Long.parseLong(arg.substring("--post-author=".length()));else throw new IllegalArgumentException("Usage: FootballManualSettlementImportMain [--apply] [--allow-nonfinal-fixture-status] [--post-author=ID]");}
        Path path=Path.of(System.getProperty("manual.csv","data/football-final-11-manual-review-final.csv"));var allRows=new FootballManualDecisionImporter().parseReviewRows(Files.readAllLines(path,StandardCharsets.UTF_8));final Long selectedAuthor=postAuthor;var rows=selectedAuthor==null?allRows:allRows.stream().filter(r->r.postAuthor()==selectedAuthor).toList();if(rows.isEmpty())throw new IllegalArgumentException("No CSV rows for PostAuthor="+selectedAuthor);var repo=new FootballSettlementRepository(new Database(AppConfig.fromEnvironment()));var result=preflight(rows,repo,override);
        System.out.println("MODE="+(apply?"APPLY":"DRY_RUN"));System.out.println("ALLOW_NONFINAL_FIXTURE_STATUS="+override);System.out.println("CSV_TOTAL_ROWS="+allRows.size());System.out.println("POST_AUTHOR="+(selectedAuthor==null?"ALL":selectedAuthor));printPreflight(rows,result);if(!apply){System.out.println("DATABASE_WRITES=0");return;}
        long decisions=rows.stream().filter(r->!r.decision().equals("SKIP")).count();
        if(!result.errors().isEmpty()||result.found()!=rows.size()||result.matching()!=rows.size()||result.already()+result.would()!=decisions||result.skipped()!=rows.size()-decisions){System.out.println("TRANSACTION=NOT_RUN");System.out.println("DATABASE_WRITES=0");return;}
        var updates=rows.stream().filter(r->result.updateIds().contains(r.legId())).map(r->new FootballSettlementRepository.ManualSettlementUpdate(r.legId(),r.betId(),SettlementDecision.valueOf(r.decision()),r.comment())).toList();var applied=repo.applyManualExact(updates);System.out.println("APPLY:");System.out.println("W="+applied.winLegs());System.out.println("L="+applied.lossLegs());System.out.println("V="+applied.voidLegs());System.out.println("updated="+applied.updatedLegs());System.out.println("alreadyInTargetState="+result.already());System.out.println("fixtureStatusOverridden="+result.overridden());if(applied.updatedLegs()!=result.would()||applied.skippedLegs()!=0)throw new IllegalStateException("manual apply mismatch; transaction rolled back: "+applied);System.out.println("TRANSACTION=COMMITTED");System.out.println("DATABASE_WRITES="+applied.updatedLegs());verifyPostApply(rows,repo);
    }
    private static Preflight preflight(List<FootballManualDecisionImporter.ReviewRow> rows,FootballSettlementRepository repo,boolean override)throws Exception{return preflight(rows,repo.findManualCandidates(rows.stream().map(FootballManualDecisionImporter.ReviewRow::legId).collect(Collectors.toSet())),override);}
    static Preflight preflight(List<FootballManualDecisionImporter.ReviewRow> rows,List<FootballSettlementRepository.ManualCandidate> dbRows,boolean override)throws Exception{Map<Long,List<FootballSettlementRepository.ManualCandidate>>by=dbRows.stream().collect(Collectors.groupingBy(FootballSettlementRepository.ManualCandidate::legId));int missing=0,duplicate=0,found=0,matching=0,mismatch=0,already=0,would=0,skipped=0,overridden=0;Set<Long>updateIds=new LinkedHashSet<>();Map<String,Integer> statuses=new TreeMap<>();List<String> errors=new ArrayList<>();for(var row:rows){var ms=by.getOrDefault(row.legId(),List.of());if(ms.isEmpty()){missing++;errors.add("missing LegId="+row.legId());continue;}if(ms.size()!=1){duplicate++;errors.add("duplicate LegId="+row.legId());continue;}found++;var c=ms.getFirst();String actual=FootballManualReviewClassifier.fingerprint(c.legId(),c.betId(),c.title());boolean legacy=row.stateFingerprint().equals(c.sourceFingerprint());if(!actual.equals(row.stateFingerprint())&&!legacy){mismatch++;errors.add("fingerprint mismatch LegId="+row.legId()+" csv="+row.stateFingerprint()+" current="+actual);continue;}matching++;if(c.betId()!=row.betId()||c.postId()!=row.postId()||c.postAuthor()!=row.postAuthor()||!Objects.equals(c.title(),row.title())){errors.add("identity mismatch LegId="+row.legId()+" csvAuthor="+row.postAuthor()+" dbAuthor="+c.postAuthor());continue;}if(row.decision().equals("SKIP")){if(!c.settlementStatus().equals("PENDING")||!c.settlementSource().equals("NONE")){errors.add("CONFLICT SKIP LegId="+row.legId()+" current="+c.settlementStatus()+"/"+c.settlementSource());continue;}skipped++;continue;}if(c.settlementStatus().equals(row.decision())&&c.settlementSource().equals("MANUAL")){if(!Objects.equals(c.manualNote(),row.comment())){errors.add("manual note mismatch LegId="+row.legId());continue;}already++;continue;}if(!c.settlementStatus().equals("PENDING")||!c.settlementSource().equals("NONE")){errors.add("CONFLICT LegId="+row.legId()+" current="+c.settlementStatus()+"/"+c.settlementSource());continue;}if(!fixtureStatusAllowed(c.statusShort(),override)){errors.add("unfinished LegId="+row.legId()+" status="+c.statusShort());continue;}if(c.statusShort()!=null&&!isFinalFixtureStatus(c.statusShort())){overridden++;statuses.merge(c.statusShort(),1,Integer::sum);}would++;updateIds.add(row.legId());}return new Preflight(found,missing,duplicate,matching,mismatch,already,would,skipped,overridden,statuses,List.copyOf(errors),Set.copyOf(updateIds));}
    private static void printPreflight(List<FootballManualDecisionImporter.ReviewRow>rows,Preflight r){var d=rows.stream().collect(Collectors.groupingBy(FootballManualDecisionImporter.ReviewRow::decision,TreeMap::new,Collectors.counting()));var u=rows.stream().filter(x->r.updateIds().contains(x.legId())).collect(Collectors.groupingBy(FootballManualDecisionImporter.ReviewRow::decision,TreeMap::new,Collectors.counting()));System.out.println("CSV:");System.out.println("totalRows="+rows.size());System.out.println("W="+d.getOrDefault("W",0L));System.out.println("L="+d.getOrDefault("L",0L));System.out.println("V="+d.getOrDefault("V",0L));System.out.println("SKIP="+d.getOrDefault("SKIP",0L));System.out.println("PRE_FLIGHT:");System.out.println("found="+r.found());System.out.println("missing="+r.missing());System.out.println("duplicate="+r.duplicate());System.out.println("fingerprintMatching="+r.matching());System.out.println("fingerprintMismatch="+r.mismatch());System.out.println("errors="+r.errors().size());r.errors().forEach(System.out::println);System.out.println("Fixture status override:");r.statuses().forEach((s,n)->System.out.println(s+"="+n));System.out.println("overridden="+r.overridden());System.out.println("Planned changes:");System.out.println("alreadyInTargetState="+r.already());System.out.println("wouldUpdate="+r.would());System.out.println("wouldUpdate.W="+u.getOrDefault("W",0L));System.out.println("wouldUpdate.L="+u.getOrDefault("L",0L));System.out.println("wouldUpdate.V="+u.getOrDefault("V",0L));System.out.println("skipped="+r.skipped());}
    private static void verifyPostApply(List<FootballManualDecisionImporter.ReviewRow>rows,FootballSettlementRepository repo){Set<Long>ids=rows.stream().map(FootballManualDecisionImporter.ReviewRow::legId).collect(Collectors.toSet());var db=repo.findManualCandidates(ids);Map<Long,FootballManualDecisionImporter.ReviewRow>csv=rows.stream().collect(Collectors.toMap(FootballManualDecisionImporter.ReviewRow::legId,x->x));int w=0,l=0,v=0,pending=0,other=0,match=0,notes=0,noteMatch=0,manual=0;long decisions=rows.stream().filter(r->!r.decision().equals("SKIP")).count();for(var c:db){var r=csv.get(c.legId());if(c.settlementStatus().equals("W"))w++;else if(c.settlementStatus().equals("L"))l++;else if(c.settlementStatus().equals("V"))v++;else if(c.settlementStatus().equals("PENDING"))pending++;else other++;if(r!=null&&!r.decision().equals("SKIP")&&c.settlementStatus().equals(r.decision()))match++;if(c.settlementSource().equals("MANUAL"))manual++;if(r!=null&&!r.decision().equals("SKIP")&&!r.comment().isBlank()){notes++;if(Objects.equals(r.comment(),c.manualNote()))noteMatch++;}}System.out.println("DB VERIFY:");System.out.println("W="+w);System.out.println("L="+l);System.out.println("V="+v);System.out.println("PENDING="+pending);System.out.println("other="+other);System.out.println("matchingCsvDecision="+match);System.out.println("mismatch="+(decisions-match));System.out.println("manualNotesExpected="+notes);System.out.println("manualNotesMatching="+noteMatch);System.out.println("manualSettlementSource="+manual+"/"+decisions);}
    record Preflight(int found,int missing,int duplicate,int matching,int mismatch,int already,int would,int skipped,int overridden,Map<String,Integer> statuses,List<String> errors,Set<Long> updateIds){ }
}
