package pl.zagranietyper.repository;

import com.fasterxml.jackson.databind.ObjectMapper;import pl.zagranietyper.model.FootballFixtureEventsSnapshot;import java.sql.*;import java.util.*;

public final class FootballFixtureEventsRepository {
 private final Database database;private final ObjectMapper mapper;public FootballFixtureEventsRepository(Database database,ObjectMapper mapper){this.database=database;this.mapper=mapper;}
 public boolean store(FootballFixtureEventsSnapshot s){try(Connection c=database.openConnection()){c.setAutoCommit(false);try{var existing=lockStatus(c,s.fixtureId());if(!shouldReplace(existing.orElse(null),s.status())){c.rollback();return false;}upsertFetch(c,s);if(s.status()==FootballFixtureEventsSnapshot.FetchStatus.COMPLETE){try(var ps=c.prepareStatement("DELETE FROM api_football_fixture_events WHERE fixture_id=?")){ps.setLong(1,s.fixtureId());ps.executeUpdate();}insertEvents(c,s);}c.commit();return true;}catch(Exception e){c.rollback();throw e;}}catch(Exception e){throw new IllegalStateException("Could not store fixture events snapshot",e);}}
 public Optional<FootballFixtureEventsSnapshot.FetchStatus>loadStatus(long fixtureId){try(Connection c=database.openConnection();var ps=c.prepareStatement("SELECT status FROM api_football_fixture_event_fetches WHERE fixture_id=?")){ps.setLong(1,fixtureId);try(var rs=ps.executeQuery()){return rs.next()?Optional.of(FootballFixtureEventsSnapshot.FetchStatus.valueOf(rs.getString(1))):Optional.empty();}}catch(SQLException e){throw new IllegalStateException(e);}}
 public List<FootballFixtureEventsSnapshot.Event>loadEvents(long fixtureId){String sql="SELECT source_index,team_id,team_name,player_id,player_name,assist_player_id,assist_name,event_type,event_detail,minute,extra_minute,comments FROM api_football_fixture_events WHERE fixture_id=? ORDER BY source_index";try(Connection c=database.openConnection();var ps=c.prepareStatement(sql)){ps.setLong(1,fixtureId);try(var rs=ps.executeQuery()){List<FootballFixtureEventsSnapshot.Event>out=new ArrayList<>();while(rs.next())out.add(new FootballFixtureEventsSnapshot.Event(rs.getInt(1),nullableLong(rs,2),rs.getString(3),nullableLong(rs,4),rs.getString(5),nullableLong(rs,6),rs.getString(7),rs.getString(8),rs.getString(9),nullableInt(rs,10),nullableInt(rs,11),rs.getString(12)));return List.copyOf(out);}}catch(SQLException e){throw new IllegalStateException(e);}}
 public static boolean shouldReplace(FootballFixtureEventsSnapshot.FetchStatus existing,FootballFixtureEventsSnapshot.FetchStatus incoming){return existing!=FootballFixtureEventsSnapshot.FetchStatus.COMPLETE||incoming==FootballFixtureEventsSnapshot.FetchStatus.COMPLETE;}
 private Optional<FootballFixtureEventsSnapshot.FetchStatus>lockStatus(Connection c,long id)throws SQLException{try(var ps=c.prepareStatement("SELECT status FROM api_football_fixture_event_fetches WHERE fixture_id=? FOR UPDATE")){ps.setLong(1,id);try(var rs=ps.executeQuery()){return rs.next()?Optional.of(FootballFixtureEventsSnapshot.FetchStatus.valueOf(rs.getString(1))):Optional.empty();}}}
 private void upsertFetch(Connection c,FootballFixtureEventsSnapshot s)throws Exception{String sql="INSERT INTO api_football_fixture_event_fetches(fixture_id,status,source,http_status,returned_event_count,error_message,raw_json,fetched_at,parser_version)VALUES(?,?,?,?,?,?,?::jsonb,?,?) ON CONFLICT(fixture_id)DO UPDATE SET status=EXCLUDED.status,source=EXCLUDED.source,http_status=EXCLUDED.http_status,returned_event_count=EXCLUDED.returned_event_count,error_message=EXCLUDED.error_message,raw_json=EXCLUDED.raw_json,fetched_at=EXCLUDED.fetched_at,parser_version=EXCLUDED.parser_version WHERE api_football_fixture_event_fetches.status<>'COMPLETE' OR EXCLUDED.status='COMPLETE'";try(var ps=c.prepareStatement(sql)){ps.setLong(1,s.fixtureId());ps.setString(2,s.status().name());ps.setString(3,s.source());if(s.httpStatus()==null)ps.setNull(4,Types.INTEGER);else ps.setInt(4,s.httpStatus());ps.setInt(5,s.events().size());ps.setString(6,s.errorMessage());ps.setString(7,s.rawJson()==null?null:mapper.writeValueAsString(mapper.readTree(s.rawJson())));ps.setTimestamp(8,Timestamp.from(s.fetchedAt()));ps.setInt(9,s.parserVersion());ps.executeUpdate();}}
 private static void insertEvents(Connection c,FootballFixtureEventsSnapshot s)throws SQLException{String sql="INSERT INTO api_football_fixture_events(fixture_id,source_index,team_id,team_name,player_id,player_name,assist_player_id,assist_name,event_type,event_detail,minute,extra_minute,comments,source,fetched_at,parser_version)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(fixture_id,source_index)DO UPDATE SET team_id=EXCLUDED.team_id,team_name=EXCLUDED.team_name,player_id=EXCLUDED.player_id,player_name=EXCLUDED.player_name,assist_player_id=EXCLUDED.assist_player_id,assist_name=EXCLUDED.assist_name,event_type=EXCLUDED.event_type,event_detail=EXCLUDED.event_detail,minute=EXCLUDED.minute,extra_minute=EXCLUDED.extra_minute,comments=EXCLUDED.comments,source=EXCLUDED.source,fetched_at=EXCLUDED.fetched_at,parser_version=EXCLUDED.parser_version";try(var ps=c.prepareStatement(sql)){for(var e:s.events()){ps.setLong(1,s.fixtureId());ps.setInt(2,e.sourceIndex());setLong(ps,3,e.teamId());ps.setString(4,e.teamName());setLong(ps,5,e.playerId());ps.setString(6,e.playerName());setLong(ps,7,e.assistPlayerId());ps.setString(8,e.assistName());ps.setString(9,e.type());ps.setString(10,e.detail());setInt(ps,11,e.minute());setInt(ps,12,e.extraMinute());ps.setString(13,e.comments());ps.setString(14,s.source());ps.setTimestamp(15,Timestamp.from(s.fetchedAt()));ps.setInt(16,s.parserVersion());ps.addBatch();}ps.executeBatch();}}
 private static void setLong(PreparedStatement p,int i,Long v)throws SQLException{if(v==null)p.setNull(i,Types.BIGINT);else p.setLong(i,v);}private static void setInt(PreparedStatement p,int i,Integer v)throws SQLException{if(v==null)p.setNull(i,Types.INTEGER);else p.setInt(i,v);}private static Long nullableLong(ResultSet r,int i)throws SQLException{long v=r.getLong(i);return r.wasNull()?null:v;}private static Integer nullableInt(ResultSet r,int i)throws SQLException{int v=r.getInt(i);return r.wasNull()?null:v;}
}
