package pl.zagranietyper.repository;

import pl.zagranietyper.model.*;
import java.sql.*;
import java.time.Instant;
import java.util.*;

public final class FootballPeriodStatisticsRepository {
    private final Database db; public FootballPeriodStatisticsRepository(Database db){this.db=db;}
    public void storeMapping(long fixture,String provider,String event,String status,String evidence){String q="INSERT INTO football_secondary_fixture_mappings(fixture_id,provider,provider_event_id,status,evidence)VALUES(?,?,?,?,?) ON CONFLICT(fixture_id,provider)DO UPDATE SET provider_event_id=EXCLUDED.provider_event_id,status=EXCLUDED.status,evidence=EXCLUDED.evidence,mapped_at=NOW()";try(Connection c=db.openConnection();var p=c.prepareStatement(q)){p.setLong(1,fixture);p.setString(2,provider);p.setString(3,event);p.setString(4,status);p.setString(5,evidence);p.executeUpdate();}catch(SQLException e){throw new IllegalStateException(e);}}
    public Optional<String> mappedEvent(long fixture,String provider){try(Connection c=db.openConnection();var p=c.prepareStatement("SELECT provider_event_id FROM football_secondary_fixture_mappings WHERE fixture_id=? AND provider=? AND status='MAPPED'")){p.setLong(1,fixture);p.setString(2,provider);try(var r=p.executeQuery()){return r.next()?Optional.ofNullable(r.getString(1)):Optional.empty();}}catch(SQLException e){throw new IllegalStateException(e);}}
    public void store(FootballPeriodStatisticsSnapshot s){try(Connection c=db.openConnection()){c.setAutoCommit(false);try{String old=null;try(var p=c.prepareStatement("SELECT status FROM football_period_stat_fetches WHERE fixture_id=? AND provider=? FOR UPDATE")){p.setLong(1,s.fixtureId());p.setString(2,s.provider());try(var r=p.executeQuery()){if(r.next())old=r.getString(1);}}if("COMPLETE".equals(old)&&s.status()!=FootballPeriodStatisticsSnapshot.FetchStatus.COMPLETE){c.rollback();return;}try(var p=c.prepareStatement("INSERT INTO football_period_stat_fetches(fixture_id,provider,provider_event_id,status,raw_json,fetched_at,parser_version)VALUES(?,?,?,?,?::jsonb,?,1) ON CONFLICT(fixture_id,provider)DO UPDATE SET provider_event_id=EXCLUDED.provider_event_id,status=EXCLUDED.status,raw_json=EXCLUDED.raw_json,fetched_at=EXCLUDED.fetched_at,updated_at=NOW()")){p.setLong(1,s.fixtureId());p.setString(2,s.provider());p.setString(3,s.providerEventId());p.setString(4,s.status().name());p.setString(5,s.rawJson());p.setTimestamp(6,Timestamp.from(s.fetchedAt()));p.executeUpdate();}if(s.status()==FootballPeriodStatisticsSnapshot.FetchStatus.COMPLETE){try(var p=c.prepareStatement("DELETE FROM football_period_statistics WHERE fixture_id=? AND provider=?")){p.setLong(1,s.fixtureId());p.setString(2,s.provider());p.executeUpdate();}String q="INSERT INTO football_period_statistics(fixture_id,provider,provider_event_id,period,statistic_type,team_side,value,value_status,raw_key,ingested_at)VALUES(?,?,?,?,?,?,?,?,?,?)";try(var p=c.prepareStatement(q)){for(var v:s.values()){p.setLong(1,s.fixtureId());p.setString(2,s.provider());p.setString(3,s.providerEventId());p.setString(4,v.period().name());p.setString(5,v.type().name());p.setString(6,v.side().name());p.setBigDecimal(7,v.value());p.setString(8,v.status().name());p.setString(9,v.rawKey());p.setTimestamp(10,Timestamp.from(s.fetchedAt()));p.addBatch();}p.executeBatch();}}c.commit();}catch(Exception e){c.rollback();throw e;}}catch(Exception e){throw new IllegalStateException(e);}}
    public Optional<FootballPeriodStatisticsSnapshot>load(long fixture,String provider){String q="SELECT provider_event_id,status,raw_json,fetched_at FROM football_period_stat_fetches WHERE fixture_id=? AND provider=?";try(Connection c=db.openConnection();var p=c.prepareStatement(q)){p.setLong(1,fixture);p.setString(2,provider);try(var r=p.executeQuery()){if(!r.next())return Optional.empty();String event=r.getString(1),status=r.getString(2),raw=r.getString(3);Instant at=r.getTimestamp(4).toInstant();List<FootballPeriodStatisticsSnapshot.Value>v=new ArrayList<>();try(var x=c.prepareStatement("SELECT period,statistic_type,team_side,value,value_status,raw_key FROM football_period_statistics WHERE fixture_id=? AND provider=?")){x.setLong(1,fixture);x.setString(2,provider);try(var z=x.executeQuery()){while(z.next())v.add(new FootballPeriodStatisticsSnapshot.Value(FootballPeriodStatisticsSnapshot.Period.valueOf(z.getString(1)),FootballFixtureStatisticType.valueOf(z.getString(2)),FootballFixtureStatisticsSnapshot.TeamSide.valueOf(z.getString(3)),z.getBigDecimal(4),FootballFixtureStatisticsSnapshot.ValueStatus.valueOf(z.getString(5)),z.getString(6)));}}return Optional.of(new FootballPeriodStatisticsSnapshot(fixture,provider,event,FootballPeriodStatisticsSnapshot.FetchStatus.valueOf(status),raw,at,v));}}catch(SQLException e){throw new IllegalStateException(e);}}
}
