package pl.zagranietyper.service;
import pl.zagranietyper.model.*;import pl.zagranietyper.parser.FootballEventPlayerPositiveSyntaxAdapter;import pl.zagranietyper.repository.FootballFixtureEventsRepository;import java.util.*;

/** Positive-evidence-only player settlement. Absence always remains UNSUPPORTED. */
public final class FootballEventPlayerPositiveSettlementEngine {
 private final FootballEventPlayerResolver resolver=new FootballEventPlayerResolver();
 public Result settle(FootballEventPlayerPositiveSyntaxAdapter.Family family,String label,FootballFixtureEventsRepository.FixtureTimeline timeline){if(family==null||timeline==null||timeline.status()!=FootballFixtureEventsSnapshot.FetchStatus.COMPLETE)return unsupported(Reason.MISSING_DATA,null);var resolution=resolver.resolve(label,timeline.events());if(!resolution.resolved())return unsupported(resolution.status()==FootballEventPlayerResolver.Status.AMBIGUOUS?Reason.AMBIGUOUS_PLAYER:Reason.UNRESOLVED_PLAYER,resolution);for(var e:timeline.events()){if(family==FootballEventPlayerPositiveSyntaxAdapter.Family.ANYTIME_SCORER&&validOrdinaryGoal(e)&&resolution.playerId().equals(e.playerId()))return win(resolution,e);if(family==FootballEventPlayerPositiveSyntaxAdapter.Family.PLAYER_ASSIST&&validAssistGoal(e)&&resolution.playerId().equals(e.assistPlayerId()))return win(resolution,e);}return unsupported(Reason.NO_POSITIVE_EVENT,resolution);}
 private static boolean validOrdinaryGoal(FootballFixtureEventsSnapshot.Event e){return"goal".equalsIgnoreCase(e.type())&&!"missed penalty".equalsIgnoreCase(e.detail())&&!"own goal".equalsIgnoreCase(e.detail());}private static boolean validAssistGoal(FootballFixtureEventsSnapshot.Event e){return"goal".equalsIgnoreCase(e.type())&&!"missed penalty".equalsIgnoreCase(e.detail())&&e.assistPlayerId()!=null;}private static Result win(FootballEventPlayerResolver.Resolution r,FootballFixtureEventsSnapshot.Event e){return new Result(SettlementDecision.W,Reason.MATCHED,r,e);}private static Result unsupported(Reason x,FootballEventPlayerResolver.Resolution r){return new Result(SettlementDecision.UNSUPPORTED,x,r,null);}public enum Reason{MATCHED,MISSING_DATA,AMBIGUOUS_PLAYER,UNRESOLVED_PLAYER,NO_POSITIVE_EVENT}public record Result(SettlementDecision decision,Reason reason,FootballEventPlayerResolver.Resolution player,FootballFixtureEventsSnapshot.Event event){}
}
