package pl.zagranietyper.service;
import pl.zagranietyper.model.FootballFixtureEventsSnapshot;import java.text.Normalizer;import java.util.*;

/** Fixture-local exact player resolution. No aliases, fuzzy matching, or cross-fixture identity. */
public final class FootballEventPlayerResolver {
 public Resolution resolve(String label,List<FootballFixtureEventsSnapshot.Event>events){String q=normalize(label);if(q.isBlank())return unresolved();Map<Long,Set<String>>names=new HashMap<>();for(var e:events){add(names,e.playerId(),e.playerName());add(names,e.assistPlayerId(),e.assistName());}Set<Long>matches=new HashSet<>();for(var entry:names.entrySet())if(entry.getValue().stream().anyMatch(n->matches(q,n)))matches.add(entry.getKey());if(matches.size()!=1)return new Resolution(matches.size()>1?Status.AMBIGUOUS:Status.UNRESOLVED,null,null);long id=matches.iterator().next();String name=names.get(id).stream().sorted(Comparator.comparingInt(String::length).reversed()).findFirst().orElse("");return new Resolution(Status.RESOLVED,id,name);}
 private static boolean matches(String q,String n){if(q.equals(n))return true;String qs=surname(q),ns=surname(n);if(!qs.equals(ns))return false;if(!q.contains(" "))return true;String[]a=q.split(" "),b=n.split(" ");return a.length==2&&b.length>=2&&a[0].length()==1&&b[0].length()>=1&&a[0].charAt(0)==b[0].charAt(0);}
 private static void add(Map<Long,Set<String>>m,Long id,String name){if(id!=null&&name!=null&&!name.isBlank())m.computeIfAbsent(id,x->new HashSet<>()).add(normalize(name));}private static String surname(String s){int i=s.indexOf(' ');return i<0?s:s.substring(i+1);}public static String normalize(String s){if(s==null)return"";return Normalizer.normalize(s.replace('ł','l').replace('Ł','L'),Normalizer.Form.NFD).replaceAll("\\p{M}+","").toLowerCase(Locale.ROOT).replaceAll("[^\\p{L}\\p{N}]+"," ").replaceAll("\\s+"," ").trim();}private static Resolution unresolved(){return new Resolution(Status.UNRESOLVED,null,null);}public enum Status{RESOLVED,AMBIGUOUS,UNRESOLVED}public record Resolution(Status status,Long playerId,String canonicalName){public boolean resolved(){return status==Status.RESOLVED;}}
}
